
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 20 19:19:45 EST 2006
//----------------------------------------------------

package edu.gsu.cs.drc;

/** CUP generated class containing symbol constants. */
public class DRCsym {
  /* terminals */
  public static final int AND = 11;
  public static final int FORALL = 10;
  public static final int COMPARISON = 14;
  public static final int OR = 12;
  public static final int RBRACE = 7;
  public static final int RPAREN = 5;
  public static final int NOT = 13;
  public static final int ERROR = 8;
  public static final int NAME = 17;
  public static final int LPAREN = 4;
  public static final int LBRACE = 6;
  public static final int STRING = 16;
  public static final int COMMA = 2;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int error = 1;
  public static final int EXISTS = 9;
  public static final int BAR = 3;
}

